version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: masstransit/rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'